services:
  app:
    build: .
    container_name: anti-social-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/antisocial
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: anti-social-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: anti-social-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  mongo_data: